{% set name = "redbird" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redbird-{{ version }}.tar.gz
  sha256: 7ed1268f8e87088642b83665ef6ea64eb7c7bcb5b2fa4887b2e976c282b38aea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic
    - python >=3.7
    - typing-extensions

test:
  imports:
    - redbird
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Miksus/red-bird
  doc_url: https://red-bird.readthedocs.io/
  summary: Repository Patterns for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
