{% set name = "redbird" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redbird-{{ version }}.tar.gz
  sha256: 2072fef29790ae9eabca4f7217b6f08fff7503051d571ba6f60236033150ef34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic
    - python >=3.7
    - typing-extensions

test:
  imports:
    - redbird
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Miksus/red-bird
  doc_url: https://red-bird.readthedocs.io/
  summary: Repository Patterns for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
